### ISSUE TITLE
Create a mood rating system that allows the user to enter their current mood

### ISSUE THREAD

**Issue by at00976** [stringlytyped/cloudnine#5]

**Comment by adriancttnc** [comment]
Base plan, which might not be fully followed and could end up with multiple ramifications, is :
- Create a table in the database that allows storing of a user's moods which will have a column to identify the user, one to record the mood rating (integer from 1 to 5) and a column to record the date-time of the input.

- A modal window that would pop up every 30 minutes to prompt the user to input their current mood.

- A page where the user could see their mood history.

**Comment by adriancttnc** [comment]
07-04-2020
Cloned the repository and started working on the issue.

**Comment by adriancttnc** [comment]
08-04-2020
Add ratings table and started working on modal window

**Comment by adriancttnc** [comment]
11-04-2020
Decided to follow a different path, zipped the progress and started from scratch

**Comment by adriancttnc** [comment]
11-04-2020 19:00
- Following the bits from the tutorial I had used for the authentication system, I have added a Moods table that stores username, userid, rating and datetime.
- A page where you could see and edit a user's mood history that is visible only if the user is logged on.
- When adding a new mood, the username should be filled in automatically ( for the moment it is set to TEST). The timestamp will record the current time.
- Rating input is limited to 0, 0.5 and 1. Have tried for about two hours to make radio buttons work, but I could not get them to feed the right information where it should. 
It would do 
`"mood"=>{"username"=>"TEST",  "when"=>"2020-04-11 18:56:15 +0100"},"rating"=>"Input 0, 0.5 or 1", "commit"=>"Create"}`

instead of 
`"mood"=>{"username"=>"TEST", "rating"=>"Input 0, 0.5 or 1", "when"=>"2020-04-11 18:56:15 +0100"}, "commit"=>"Create"}`

For now the rating is to be inserted into a form field that has limited input.

**Comment by adriancttnc** [comment]
11:04-2020 20:00
- Added a chart to the mood history list using the gem ChartKick.

**Comment by mohammedmaks** [comment]
17-04-2020 18:30

After taking over work from @adriancttnc (Adrian) on 10-04-2020, we agreed i would work on implementing the modal window for the mood rating system. This would allow users to click on an image from the modal pop up every 30 minutes or so & automatically have their answers recorded to the database.

Progress:

- As of today I have struggled to get the bootstrap modal window to show up either on button click or on javascript response which has severely halted progress. This seems to be a common issue according to StackOverflow.

- I have been able to work almost blindly & still setup the modal window images to automatically log & record a response for the user based on the inputs. Although, i have not been able to apply any CSS to this as i can not see the modal window.

Issues:

- When i take out the   `<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>` line i am able to see the modal window & can work on it from there. This tells me the issue is in relation to that stylesheet although i still cant find it.

Next Steps
- As of now the only issue is getting the modal window to show up & display on timer.

- Therefore, i aim to sort out that issue & then apply CSS & finishing touches to the section of work before committing changes.

**Comment by stringlytyped** [comment]
I have finished reviewing your contributions and performed some general clean-up. The unnecessary scaffolding was removed, leaving only the controller actions that are needed. The chart was tweaked to only show data for the currently logged in user.

As there was no mechanism to allow the user to rate their mood, I added a simple partial in `app/views/playlist/_mood_rater.html.erb` to facilitate this. This is backed by the `mood_ratings#create` controller action which only allows mood ratings to be stored for the currently logged in user.

I could not see the code for the modal window described further up in the thread. Perhaps there are some commits that weren't pushed to the remote repo? Regardless, that functionality is currently beyond the scope of the project (reminders are a stretch goal—see item m. in section 03.04 of the project definition).
