### ISSUE TITLE
Use the Dark Sky API to get the current weather

### ISSUE THREAD

**Issue by at00976** [stringlytyped/cloudnine#6]

**Comment by at00976** [comment]
https://github.com/darkskyapp/darksky-ruby - This link has a bit of information on the Dark Sky API gem that might help with development

**Comment by AliBaba1301** [comment]
Dark sky API no longer available will look into other weather APIs that can be used instead.

**Comment by AliBaba1301** [comment]
After researching several new weather APIs have decided to use open weather instead as it is freely available.
https://openweathermap.org/api

**Comment by AliBaba1301** [comment]
signed up to the API

API Key: cb133295b04bc2c8c6ab41f01d95566c

**Comment by AliBaba1301** [comment]
Had several issues trying to convert to the openweathermap API. Just gonna start from scratch rather than trying to adjust the darksky stuff.

**Comment by vanesadok** [comment]
Using the 'Current weather data' API and call it by using geographic coordinates (lat and lon) seems like the best fit for our task at hand.

**Comment by vanesadok** [comment]
Currently trying to implement to show the json code of the data on a view when loading the page, error that I am getting is: Failed to open TCP connection to http:80 (getaddrinfo: Name or service not known)

**Comment by vanesadok** [comment]
instead of using Net::HTTP, I am trying using httparty

**Comment by vanesadok** [comment]
I get the same error using Httparty

**Comment by vanesadok** [comment]
I have now resolved the issue, using Net::HTTP. I have a view that shows the data from the api url in json format

**Comment by vanesadok** [comment]
or sorry shows it as an ruby array, with rusby hashes inside, since it parsed the json file

**Comment by vanesadok** [comment]
Playing around with showing just a specific value, e.g. location, weather from that data

**Comment by vanesadok** [comment]
Next step would be to implement something where the user can enter their location so it shows the weather for that area, and not inly using a static url for displaying the data, where I need to change in the controller file the url link

**Comment by AliBaba1301** [comment]
Whilst implementing a system so the user can enter their location. I referred to the documentary for the OpenWeatherMap API and found weather can be queried for both city and zip code. As the zip code provides a more localised weather response. I decided to use the zip code search. However, on testing several postcodes I was unable to get the weather to appear. Due to this, I modified my code to request the input of a city name and output the general weather for that city as it is unlikely to vary too much across a city I believe this is an acceptable fix.

**Comment by stringlytyped** [comment]
I have made a number of changes to the weather code to prepare it for the merge into master:

- Generated a new OpenWeather API Key and saved it in the encrypted Rails credentials store. **API keys/secrets should never be committed to source control or posted in a public discussion like this GitHub issue.** @AliBaba1301 you will need to log into your OpenWeather account and delete the API key because anyone that comes across this issue will be able to use the key you posted above to impersonate you (which could get us banned from the OpenWeather service).

- I was originally going to replace the Net::HTTP code with an [OpenWeather gem](https://github.com/coderhs/ruby_open_weather_map) but I couldn't get it to work (it kept returning data for the wrong city). Instead, I moved the code for fetching data from the API into a new `OpenWeather` class in the `lib` directory.

- Tweaked the Net::HTTP code to make requests using TLS, specify a timeout, and handle HTTP responses other than 200.

- Added a new Location model to represent the city/town of a user and the weather data associated with the city/town.

- Added a preferences controller and view for configuring user preferences. Moved the form for configuring the user's location out of the home view/controller into the preferences view/controller.

- Added a simple partial in `app/views/playlists/_weather.html.erb` for displaying weather data to the user.

I still need to add code for streaming new weather data to the client when it changes (this functionality is needed in order to meet the requirements of the project as defined in the project plan).

**Comment by stringlytyped** [comment]
I've added code to allow regular weather updates to be delivered to the client over WebSocket, thereby meeting sponsor requirement e (see section 03.02 of the project definition). This is implemented using the following classes:

**`WeatherChannel`**: Defines a new ActionCable channel for delivering updates and handles subscribe and unsubscribe events. When a client subscribes, a future update is scheduled with `WeatherUpdateJob.schedule`.

**`WeatherBroadcastJob`**: We don't want weather update broadcasts to happen in the main thread of the application, so this class performs them in the background. When a broadcast is delivered, another future update is scheduled with `WeatherUpdateJob.schedule`

**`WeatherUpdateJob`**: The OpenWeather API needs to be polled for new data on a regular basis. This class keeps track of these scheduled jobs.

**`Location`**: An `after_update_commit` callback has been added to the Location class to broadcast updates using `WeatherBroadcastJob` when the weather data for the location changes.

Some JavaScript has also been added in the `app/javascript/channels/weather_channel.js` file. This code subscribes to the `WeatherChannel` and updates the weather partial when a new broadcast message is received.
